steps:
  # Configure kubectl
- name: gcr.io/cloud-builders/kubectl
  args:
    - cluster-info
  env:
    - CLOUDSDK_COMPUTE_REGION=$_COMPUTE_LOCATION
    - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME
    - KUBECONFIG=/workspace/.kube/config
  # Deploy to production
- name: gcr.io/$PROJECT_ID/helm
  id: Deploy chart
  args:
    - upgrade
    - -i
    - data-commons
    - $_CHART_LOCATION
    - -n
    - $_NAMESPACE
  env:
    - KUBECONFIG=/workspace/.kube/config
    - TILLERLESS=true
substitutions:
  _COMPUTE_LOCATION: us-east4
  _CLUSTER_NAME: live-k8s-cluster-ezyd
  _CHART_LOCATION: deploy/helm_charts/dc_website
  _NAMESPACE: data-commons
options:
  logging: CLOUD_LOGGING_ONLY
