steps:
  # Configure the SSH client
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  # Configure kubectl
- name: gcr.io/cloud-builders/kubectl
  args:
    - cluster-info
  env:
    - CLOUDSDK_COMPUTE_REGION=$_COMPUTE_LOCATION
    - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME
    - KUBECONFIG=/workspace/.kube/config
  # Deploy to production
- name: gcr.io/$PROJECT_ID/helm
  id: Deploy chart
  args:
    - upgrade
    - -i
    - data-commons
    - $_CHART_LOCATION
    - -n
    - $_NAMESPACE
  env:
    - KUBECONFIG=/workspace/.kube/config
    - TILLERLESS=true
substitutions:
  _IMAGE_LOCATION: us
  _COMPUTE_LOCATION: us-east4
  _REPO_NAME: datacommons
  _PROJECT_ID: one-data-commons
  _APP_NAME: website-compose
  _CLUSTER_NAME: live-k8s-cluster-ezyd
  _CHART_LOCATION: deploy/helm_charts/dc_website
  _NAMESPACE: data-commons
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github-ssh-key/versions/latest
    env: 'SSH_KEY'
options:
  logging: CLOUD_LOGGING_ONLY
