steps:
  # Configure the SSH client
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  # Update submodules
- name: gcr.io/cloud-builders/git
  args: ['submodule', 'update', '--init', '--recursive']
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  # Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_APP_NAME}:${SHORT_SHA}', '-f', 'build/web_compose/Dockerfile', '.']
  # Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_APP_NAME}:${SHORT_SHA}']
  # Update the image tag in the Helm Chart
- name: 'linuxserver/yq'
  args:
    - 'yq'
    - 'write'
    - '-i'
    - 'deploy/helm_charts/dc_website/values.yaml'
    - 'website.image.tag'
    - '${SHORT_SHA}'
  # Configure kubectl
- name: gcr.io/cloud-builders/kubectl
  args:
    - cluster-info
  env:
    - CLOUDSDK_COMPUTE_REGION=$_LOCATION
    - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME
    - KUBECONFIG=/workspace/.kube/config
  # Deploy the image to staging
- name: gcr.io/$PROJECT_ID/helm
  id: Deploy chart
  args:
    - upgrade
    - -i
    - data-commons
    - $_CHART_LOCATION
    - -f
    - $_VALUES_FILE
    - -n
    - $_NAMESPACE
  env:
    - KUBECONFIG=/workspace/.kube/config
    - TILLERLESS=true
  # Commit Chart changes
- name: gcr.io/cloud-builders/git
  args:
    - commit
    - -a
    - -m
    - "Update image tag - $SHORT_SHA - [ci skip]"
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  # Push Chart changes
- name: gcr.io/cloud-builders/git
  args:
    - push
  volumes:
  - name: 'ssh'
    path: /root/.ssh
images:
- '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_APP_NAME}:${SHORT_SHA}'
substitutions:
  _LOCATION: us-east4
  _REPO_NAME: datacommons
  _PROJECT_ID: one-data-commons
  _APP_NAME: website-compose
  _CLUSTER_NAME: staging-k8s-cluster-bngx
  _CHART_LOCATION: deploy/helm_charts/dc_website
  _VALUES_FILE: deploy/helm_charts/stagingValues.yaml
  _NAMESPACE: data-commons
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github-ssh-key/versions/latest
    env: 'SSH_KEY'

