website:
  githash: null
  image:
    project: datcom-ci
    pullPolicy: Always
    tag: latest
  flaskEnv: custom
  gcsDataPath: gs://one-datacommons-imports-prod/dec7
  iap:
    enabled: false
  replicas: 1
  redis:
    enabled: false
    configFile: null
  placeSummary:
    enabled: false
    data:
      country: null
      geoid_0_2: null
      geoid_3_5: null
      geoid_6_9: null
      wikidataId: null
      others: null
  nodePool: null
  evalTool:
    enabled: false
nameOverride: ''
fullnameOverride: ''
namespace:
  create: false
  name: data-commons
serviceAccount:
  name: website-ksa
ingress:
  name: website-ingress
  ipName: dc-website-ip
  certName: dc-website-cert
  enabled: false
mixer:
  githash: null
  image:
    project: datcom-ci
    pullPolicy: Always
    tag: null
    hostProject: null
    serviceName: null
    schemaConfigs: null
esp:
  image:
    repository: gcr.io/endpoints-release/endpoints-runtime
    tag: '2'
    pullPolicy: Always
kgStoreConfig:
  bigqueryVersion: null
  baseBigtableInfo: null
  customBigtableInfo: ''
serviceGroups:
  svg:
    urlPaths:
      - /place/stat-var-group/*
      - /stat-var/*
      - /v1/variable/*
      - /v1/bulk/info/variable-group
      - /v1/bulk/info/variable
    replicas: 1
    resources:
      memoryRequest: 8G
      memoryLimit: 8G
    cacheSVG: true
    nodePool: null
  observation:
    urlPaths:
      - /v2/observation
    replicas: 1
    resources:
      memoryRequest: 2G
      memoryLimit: 2G
    nodePool: null
  node:
    urlPaths:
      - /v2/node
    replicas: 1
    resources:
      memoryRequest: 3G
      memoryLimit: 3G
    nodePool: null
  default:
    urlPaths:
      - /*
    replicas: 1
    resources:
      memoryRequest: 2G
      memoryLimit: 2G
    nodePool: null
nl:
  enabled: false
  embeddings: null
  models: null
  memory: 2G
  workers: 1
svg:
  blocklistFile: []
nodejs:
  enabled: false
  env: gke
  replicas: null
  apiRoot: null
  nodePool: null
cronTesting:
  enabled: false
  webApiRoot: null
  nodejsRoot: null
  screenshotDomain: null
  enableSanity: true
  nodePool: null
